### ISSUE TITLE
Page 1: Refine page layout for provider breakdowns

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/apprenticeships-provider-dashboard#44]
Checklist of styling feedback to resolve on the first page:

- [ ] Provider table on the left is quite squashed 
- [ ] Dropdown options in the top right are too large / dominant

Current view of the dashboard

![image](https://github.com/user-attachments/assets/be193f0d-41dc-4f39-9b81-6529501829f8)

**Comment by axcooper** [comment]
This was resolved in another issue - 93-page-1-make-the-top-of-the-page-with-the-dropdowns-go-all-the-way-across-the-page'
