### ISSUE TITLE
Tidy up ordering and capitalisation in user selections

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/apprenticeships-provider-dashboard#47]
Bunching a few issues into one here, all around presentation of the data:

Page 1: Provider breakdowns
- [x] Capitalise options for measures. 
- [x] Default year should be most recent year, and ordered in descending order. 
- [x] Options for measures in file order rather than alphabetical. 
- [x] Regions better ordered in usual order rather than alphabetical. 

Page 2: LAD breakdowns
- [x] Capitalise options for measures.
- [x] Options for measures in file order rather than alphabetical. 
- [x] Default year should be most recent year, and ordered in descending order. 
- [x] LAD dropdowns would be better sorted alphabetically

Page 3: Subjects and standards
- [x] Default year should be most recent year, and ordered in descending order. 
- [x] Providers should be in alphabetical order in the dropdown

Page 4: Learner characteristics
- [x] Better format table headings

**Comment by axcooper** [comment]
All addressed
